"use client";
import {useEffect,useMemo,useState} from "react";
const BUILDINGS=[{id:"cursor",name:"Cursor",cost:15,cps:.1,icon:"👆"},{id:"grandma",name:"Grandma",cost:100,cps:1,icon:"👵"},{id:"farm",name:"Farm",cost:1100,cps:8,icon:"🌾"},{id:"mine",name:"Mine",cost:12000,cps:47,icon:"⛏️"},{id:"factory",name:"Factory",cost:130000,cps:260,icon:"🏭"},{id:"bank",name:"Bank",cost:1400000,cps:1400,icon:"🏦"}];
const ACH=[["first","First Batch","Bake your first cookie.",1],["hundred","Cookie Century","Reach 100 cookies.",100],["thousand","Cookie Hoarder","Reach 1,000 cookies.",1000],["million","Millionaire","Reach 1,000,000 cookies.",1000000]];
function fmt(n){if(n<1000)return Math.floor(n).toLocaleString();const u=["K","M","B","T","Qa","Qi"];let i=-1,v=n;while(v>=1000&&i<u.length-1){v/=1000;i++}return (v>=100?v.toFixed(0):v>=10?v.toFixed(1):v.toFixed(2))+u[i]}
export default function Home(){const[cookies,setCookies]=useState(0),[total,setTotal]=useState(0),[buildings,setBuildings]=useState({}),[clickPower,setClickPower]=useState(1),[pops,setPops]=useState([]),[golden,setGolden]=useState(null),[frenzy,setFrenzy]=useState(false);
const cps=useMemo(()=>BUILDINGS.reduce((s,b)=>s+(buildings[b.id]||0)*b.cps,0),[buildings]);
useEffect(()=>{try{const d=JSON.parse(localStorage.getItem("cookie-clicker-save"));if(d){setCookies(d.cookies||0);setTotal(d.total||0);setBuildings(d.buildings||{});setClickPower(d.clickPower||1)}}catch{}},[]);
useEffect(()=>{const t=setInterval(()=>{const a=cps/10*(frenzy?7:1);setCookies(v=>v+a);setTotal(v=>v+a)},100);return()=>clearInterval(t)},[cps,frenzy]);
useEffect(()=>{const t=setInterval(()=>{if(!golden&&Math.random()<.035)setGolden({x:10+Math.random()*80,y:15+Math.random()*65})},1000);return()=>clearInterval(t)},[golden]);
useEffect(()=>{const t=setInterval(()=>localStorage.setItem("cookie-clicker-save",JSON.stringify({cookies,total,buildings,clickPower})),5000);return()=>clearInterval(t)},[cookies,total,buildings,clickPower]);
function click(e){const r=e.currentTarget.getBoundingClientRect(),p={id:Date.now()+Math.random(),x:e.clientX-r.left,y:e.clientY-r.top};setPops(v=>[...v,{...p,n:clickPower}]);setCookies(v=>v+clickPower);setTotal(v=>v+clickPower);setTimeout(()=>setPops(v=>v.filter(x=>x.id!==p.id)),800)}
function buy(b){const owned=buildings[b.id]||0,cost=Math.floor(b.cost*1.15**owned);if(cookies<cost)return;setCookies(v=>v-cost);setBuildings(v=>({...v,[b.id]:owned+1}))}
function goldenClick(){setGolden(null);setFrenzy(true);setCookies(v=>v+777);setTotal(v=>v+777);setTimeout(()=>setFrenzy(false),15000)}
function reset(){if(!confirm("Reset your cookie empire?"))return;localStorage.removeItem("cookie-clicker-save");setCookies(0);setTotal(0);setBuildings({});setClickPower(1)}
return <main className="game"><header><div><h1>COOKIE<span>CLICKER</span></h1><small>Bake. Upgrade. Repeat.</small></div><div className="stats"><b>{fmt(cookies)}<small>cookies</small></b><b>{fmt(cps)}<small>per second</small></b></div></header><section className="layout"><div className="main"><div className="stage"><label>COOKIES BAKED: {fmt(total)}</label><button className="cookieBtn" onClick={click}>🍪</button>{pops.map(p=><i key={p.id} style={{left:p.x,top:p.y}}>+{fmt(p.n)}</i>)}{golden&&<button className="golden" style={{left:golden.x+"%",top:golden.y+"%"}} onClick={goldenClick}>✨</button>}{frenzy&&<strong className="frenzy">7× COOKIE FRENZY!</strong>}</div><p className="power">+{fmt(clickPower)} per click</p><div className="actions"><button onClick={()=>setClickPower(v=>v+1)}>Upgrade click (+1)</button><button onClick={reset}>Reset</button></div></div><aside className="shop"><h2>BUILDINGS</h2>{BUILDINGS.map(b=>{const owned=buildings[b.id]||0,cost=Math.floor(b.cost*1.15**owned),ok=cookies>=cost;return <button className={"building "+(ok?"ok":"")} key={b.id} onClick={()=>buy(b)}><span>{b.icon}</span><div><b>{b.name}</b><small>{b.cps} cookies/sec each</small></div><div className="right"><b>{owned}</b><small>🍪 {fmt(cost)}</small></div></button>})}</aside></section><section className="bottom"><div className="panel"><h2>🏆 Achievements</h2>{ACH.map(([id,n,d,need])=><div className={"achievement "+(total>=need?"unlocked":"")} key={id}><span>{total>=need?"🏆":"🔒"}</span><div><b>{n}</b><small>{d}</small></div></div>)}</div><div className="panel"><h2>⚡ Events</h2><p>Golden cookies randomly appear. Click one for a bonus and a temporary 7× frenzy.</p><p>Your progress automatically saves in this browser.</p></div></section><footer>Built with Next.js • Save data stays in your browser</footer></main>}