"use client";

import { useEffect, useMemo, useState } from "react";


// MEGA CONTENT PACK: deterministic data-driven systems for an original incremental universe.
const ACHIEVEMENT_PACK=Array.from({length:500},(_,i)=>({id:"mega"+i,name:["Tiny Miracle","Cosmic Hoarder","Reality Bender","Cookie Archaeologist","Empire Builder","Void Walker","Quantum Chef","Time Baron","Dream Tycoon","Universal Baker"][i%10]+" "+(i+1),target:Math.floor(10*Math.pow(1.12,i)),type:["total","clicks","owned","goldenClicks","research","relics"][i%6]}));
const EVENT_PACK=Array.from({length:80},(_,i)=>({id:"event"+i,name:["Meteor Shower","Cookiequake","Lucky Hour","Sugar Storm","Ancient Visitor","Market Boom","Time Rift","Reality Glitch"][i%8],duration:10+(i%7)*5,mult:1.2+(i%9)*.1}));
const RELIC_PACK=Array.from({length:120},(_,i)=>({id:"relic"+i,name:["Chrono Gear","Golden Crumb","Void Pearl","Star Spoon","Dream Shard","Reality Key","Quantum Fork","Eternal Rolling Pin"][i%8]+" "+(i+1),power:0.01+(i%20)*.005}));
const SPELL_PACK=Array.from({length:60},(_,i)=>({id:"spell"+i,name:["Minor Fortune","Cookie Comet","Temporal Bake","Arcane Oven","Reality Surge","Mana Harvest"][i%6],cost:20+i*15,power:1.1+(i%15)*.08}));
const QUEST_PACK=Array.from({length:200},(_,i)=>({id:"quest"+i,name:["Bake","Build","Click","Research","Trade","Ascend","Discover","Plant"][i%8]+" Contract "+(i+1),target:Math.floor(100*Math.pow(1.1,i)),reward:1+(i%10)}));
const ICONS=["👆","👵","🌾","⛏️","🏭","🏦","🏛️","🧙","🚀","⚗️","🧬","🌀","🌌","🤖","🛰️","🪐","🌋","🧊","⚡","🧠","🔮","🕳️","☀️","🌙","👽","🛸","🐉","🏰","🗿","💎"];
const NAMES=["Cursor","Baker","Grandma","Farm","Mine","Factory","Bank","Temple","Wizard Tower","Shipment","Alchemy Lab","Portal","Time Machine","Antimatter Condenser","Prism","Chancemaker","Fractal Engine","Javascript Console","Idleverse","Cortex Baker","Quantum Oven","Dream Forge","Star Bakery","Nebula Harvester","Dimension Mill","Chrono Bakery","Reality Printer","Multiverse Loom","Infinity Engine","Omnifactory","Cookie Singularity","Cosmic Kitchen","Void Brewery","Dragon Bakery","Ancient Archive","Mythic Machine","Astral Foundry","Quantum Hive","Universal Bakery","Paradox Plant","Eternal Workshop","Genesis Engine","Hypernova Oven","World Eater","Pocket Universe","Reality Compiler","Grand Archive","Omega Bakery","Absolute Oven","Transcendent Factory","Celestial Forge","Infinite Orchard","Starlight Mine","Galaxy Bank","Cosmic Temple","Oracle Tower","Wormhole Express","Dark Matter Lab","Singularity Farm","Time Orchard","Dream Factory","Memory Bank","Thought Temple","Mind Wizard","Idea Shipment","Concept Lab","Story Engine","Myth Factory","Legend Bank","Hero Temple","Titan Tower","God Machine","Heaven Forge","Afterlife Bakery","Soul Factory","Eternity Bank","Infinity Temple","Creation Engine","Chaos Lab","Order Factory","Fate Bank","Destiny Tower","Luck Machine","Fortune Forge","Probability Farm","Chance Engine","Miracle Maker","Wish Factory","Magic Bank","Wonder Temple","Mystery Tower","Secret Lab","Unknown Engine","Impossible Machine","Beyond Bakery","Absolute Reality","The Last Cookie","The First Cookie","The Cookieverse","Omniversal Oven"];
const BUILDINGS=NAMES.map((name,i)=>({id:"b"+i,name,base:Math.max(15,Math.floor(15*Math.pow(1.15,i))),cps:i===0?.1:Math.pow(10,i/5)*.8,icon:ICONS[i%ICONS.length]}));
const UPGRADE_NAMES=["Reinforced Finger","Steel Rolling Pin","Golden Dough","Quantum Flour","Chrome Oven","Baker's Gloves","Double Mixer","Turbo Kneader","Cookie Magnet","Lucky Apron","Royal Recipe","Ancient Recipe","Cosmic Recipe","Perfect Temperature","Infinite Yeast","Time-Sliced Dough","Matter Flour","Antimatter Sugar","Dream Frosting","Reality Icing"];
const UPGRADES=Array.from({length:200},(_,i)=>{const tier=Math.floor(i/20),kind=i%3;const value=kind===0?Math.max(1,Math.floor(Math.pow(2,tier/2))):kind===1?.05+tier*.02:.02+tier*.01;return{id:"u"+i,name:UPGRADE_NAMES[i%20]+" "+(i+1),desc:kind===0?"+1 to +"+value+" cookies per click":kind===1?"+"+Math.round(value*100)+"% cookie production":"+"+Math.round(value*100)+"% golden rewards",cost:Math.floor(100*Math.pow(1.62,i)),kind,value};});
const ACHIEVEMENTS=[["first","First Batch",1],["hundred","Cookie Century",100],["thousand","Cookie Hoarder",1000],["million","Millionaire",1e6],["billion","Billionaire",1e9],["trillion","Trillionaire",1e12],["build10","Small Factory",10],["build100","Industrialist",100],["build1000","Mega Empire",1000],["click100","Busy Hands",100],["click1000","Clickstorm",1000],["gold10","Golden Touch",10],["gold100","Gold Rush",100],["upgrade25","Researcher",25],["upgrade100","Master Baker",100],["ascend1","Beyond Time",1],["combo25","Combo Master",25],["combo100","Combo Legend",100]];
const fresh=()=>({cookies:0,total:0,buildings:{},clickPower:1,multiplier:1,purchased:[],clicks:0,goldenClicks:0,combo:0,bestCombo:0,heaven:0,research:0,last:Date.now(),baseCps:0,sugar:0,mana:100,maxMana:100,relics:0,crits:0,spells:0,trades:0,plants:[],season:0,market:{},wrinklers:[],wrinklerPopped:0,quests:{},researchLevels:[]});

function fmt(n){if(!Number.isFinite(n))return"∞";if(n<1000)return Math.floor(n).toLocaleString();const units=["K","M","B","T","Qa","Qi","Sx","Sp","Oc","No","Dc","Ud","Dd","Td","Qad","Qid","Sxd","Spd","Ocd","Nod"];let i=-1,v=n;while(v>=1000&&i<units.length-1){v/=1000;i++;}return(v>=100?Math.floor(v):v>=10?v.toFixed(1):v.toFixed(2))+units[i];}

export default function Home(){
 const [g,setG]=useState(fresh);const[loaded,setLoaded]=useState(false);const[tab,setTab]=useState("shop");const[pops,setPops]=useState([]);const[golden,setGolden]=useState(null);const[buff,setBuff]=useState(null);const[toast,setToast]=useState("");const[buyMode,setBuyMode]=useState(1);
 const owned=useMemo(()=>Object.values(g.buildings).reduce((a,b)=>a+b,0),[g.buildings]);
 const baseCps=useMemo(()=>BUILDINGS.reduce((s,b)=>s+(g.buildings[b.id]||0)*b.cps,0),[g.buildings]);
 const upgradeMult=1+g.purchased.reduce((s,id)=>{const u=UPGRADES.find(x=>x.id===id);return s+(u&&u.kind===1?u.value:0)},0);
 const seasonNames=["Harvest","Frost","Arcane","Cosmic","Festival"];const season=seasonNames[g.season%seasonNames.length];const plantMult=1+g.plants.length*.08;const cps=baseCps*g.multiplier*upgradeMult*plantMult*(buff?.kind==="frenzy"?7:1)*(1+g.heaven*.05)*(season==="Harvest"?1.15:1);
 const critChance=Math.min(.5,.02+g.purchased.filter(id=>{const u=UPGRADES.find(x=>x.id===id);return u&&u.kind===3}).length*.01);const clickValue=g.clickPower*g.multiplier*(buff?.kind==="click"?7:1)*(1+g.combo*.01);
 useEffect(()=>{try{const s=JSON.parse(localStorage.getItem("cookie-clicker-save"));if(s){const elapsed=Math.min(86400,Math.max(0,(Date.now()-(s.last||Date.now()))/1000));const offline=(s.baseCps||0)*elapsed*.5;setG({...fresh(),...s,cookies:(s.cookies||0)+offline,total:(s.total||0)+offline,last:Date.now()});}}catch{}setLoaded(true)},[]);
 useEffect(()=>{if(!loaded)return;const t=setInterval(()=>setG(x=>({...x,cookies:x.cookies+cps/20,total:x.total+cps/20,last:Date.now(),baseCps:cps})),50);return()=>clearInterval(t)},[loaded,cps]);
 useEffect(()=>{if(!loaded)return;const t=setInterval(()=>localStorage.setItem("cookie-clicker-save",JSON.stringify({...g,baseCps:cps,last:Date.now()})),3000);return()=>clearInterval(t)},[g,cps,loaded]);
 useEffect(()=>{const t=setInterval(()=>{if(!golden&&Math.random()<.018)setGolden({x:7+Math.random()*86,y:14+Math.random()*68,type:Math.random()<.15?"chain":"normal"});},1000);return()=>clearInterval(t)},[golden]);
 function notify(s){setToast(s);setTimeout(()=>setToast(""),2400)}
 function bake(e){const amount=clickValue*(Math.random()<critChance?10:1);const r=e.currentTarget.getBoundingClientRect();const p={id:Date.now()+Math.random(),x:e.clientX-r.left,y:e.clientY-r.top,amount};setPops(v=>[...v,p]);setTimeout(()=>setPops(v=>v.filter(q=>q.id!==p.id)),650);setG(x=>({...x,cookies:x.cookies+amount,total:x.total+amount,clicks:x.clicks+1,combo:Math.min(100,x.combo+1),bestCombo:Math.max(x.bestCombo,Math.min(100,x.combo+1))}));}
 useEffect(()=>{const t=setInterval(()=>setG(x=>({...x,combo:Math.max(0,x.combo-.5)})),100);return()=>clearInterval(t)},[]);
 function buyBuilding(b){const have=g.buildings[b.id]||0;let count=buyMode==="max"?0:buyMode,cost=0;while((buyMode==="max"?count<100:count>0)){const c=Math.floor(b.base*Math.pow(1.15,have+(buyMode==="max"?count:buyMode-count)));if(g.cookies<cost+c)break;cost+=c;if(buyMode!=="max"){count--;if(count===0)break}else count++;}const n=buyMode==="max"?count:buyMode;if(!n||g.cookies<cost)return;setG(x=>({...x,cookies:x.cookies-cost,buildings:{...x.buildings,[b.id]:have+n}}));}
 function buyUpgrade(u){if(g.purchased.includes(u.id)||g.cookies<u.cost)return;setG(x=>({...x,cookies:x.cookies-u.cost,purchased:[...x.purchased,u.id],clickPower:u.kind===0?x.clickPower+u.value:x.clickPower,multiplier:u.kind===1?x.multiplier*(1+u.value):x.multiplier}));notify("Upgrade unlocked: "+u.name);}
 function goldenHit(){if(!golden)return;let gain=777*(1+g.goldenClicks*.02);if(golden.type==="chain")gain*=Math.max(2,g.combo+2);setGolden(null);setG(x=>({...x,cookies:x.cookies+gain,total:x.total+gain,goldenClicks:x.goldenClicks+1}));const k=Math.random()<.45?"click":"frenzy";setBuff({kind:k});setTimeout(()=>setBuff(null),15000);notify(k==="frenzy"?"7× PRODUCTION FRENZY!":"7× CLICK FRENZY!");}
 function ascend(){const gain=Math.floor(Math.cbrt(g.total/1e6));if(gain<=g.heaven)return notify("Not enough cosmic progress to ascend.");if(!confirm("Ascend? Your bakery resets, but you gain "+(gain-g.heaven)+" permanent heavenly levels."))return;setG(x=>({...fresh(),heaven:gain,last:Date.now()}));notify("Ascended beyond reality.");}
 function reset(){if(!confirm("Delete this bakery forever?"))return;localStorage.removeItem("cookie-clicker-save");setG(fresh());}
 function exportSave(){try{navigator.clipboard.writeText(btoa(unescape(encodeURIComponent(JSON.stringify(g)))));notify("Save copied to clipboard.");}catch{notify("Clipboard unavailable.");}}
 function importSave(){const raw=prompt("Paste your save code:");if(!raw)return;try{const x=JSON.parse(decodeURIComponent(escape(atob(raw))));setG({...fresh(),...x,last:Date.now()});notify("Save imported.");}catch{notify("Invalid save.");}}
 function castSpell(type){const costs={luck:20,storm:60,alchemy:100};const c=costs[type];if(g.mana<c)return notify("Not enough mana.");setG(x=>({...x,mana:x.mana-c,spells:x.spells+1}));if(type==="luck"){setGolden({x:50,y:45,type:"normal"});notify("Fortune summoned a golden cookie.");}if(type==="storm"){setBuff({kind:"frenzy"});setTimeout(()=>setBuff(null),20000);notify("20 second production frenzy.");}if(type==="alchemy"){const gain=Math.max(1,cps*30);setG(x=>({...x,cookies:x.cookies+gain,total:x.total+gain}));notify("Alchemy created "+fmt(gain)+" cookies.");}}
 function tradeStock(){if(g.cookies<1000)return notify("Need 1,000 cookies to trade.");setG(x=>({...x,cookies:x.cookies-1000,total:x.total,trades:x.trades+1,relics:x.relics+(Math.random()<.1?1:0)}));notify("Market trade completed.");}
 function plant(){if(g.sugar<1)return notify("You need sugar lumps.");setG(x=>({...x,sugar:x.sugar-1,plants:[...x.plants,Date.now()],gardenLevel:(x.gardenLevel||0)+1}));notify("A new plant grew.");}
 const unlock=a=>a[0].startsWith("build")?owned>=a[2]:a[0].startsWith("click")?g.clicks>=a[2]:a[0].startsWith("gold")?g.goldenClicks>=a[2]:a[0].startsWith("upgrade")?g.purchased.length>=a[2]:a[0].startsWith("ascend")?g.heaven>=a[2]:a[0].startsWith("combo")?g.bestCombo>=a[2]:g.total>=a[2];
 return <main className="game"><header><div><h1>COOKIE<span>REALMS</span></h1><small>An original infinite incremental bakery</small></div><div className="stats"><b>{fmt(g.cookies)}<small>cookies</small></b><b>{fmt(cps)}<small>per second</small></b><b>{fmt(g.heaven)}<small>heaven</small></b></div></header>
 {toast&&<div className="toast">{toast}</div>}<nav className="tabs">{["shop","upgrades","achievements","research","garden","spells","market","seasons","ascension","stats"].map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x.toUpperCase()}</button>)}</nav>
 <section className="layout"><div className="main"><div className={"stage "+(buff?"buffed":"")}><label>TOTAL BAKED: {fmt(g.total)} • COMBO: {g.combo.toFixed(0)}</label><button className="cookieBtn" onClick={bake} aria-label="Bake cookie"><span className="cookieArt" aria-hidden="true"/></button>{pops.map(p=><i key={p.id} style={{left:p.x,top:p.y}}>+{fmt(p.amount)}</i>)}{golden&&<button className={"golden "+golden.type} style={{left:golden.x+"%",top:golden.y+"%"}} onClick={goldenHit}>✨</button>}{buff&&<strong className="frenzy">{buff.kind==="frenzy"?"7× PRODUCTION FRENZY":"7× CLICK FRENZY"}</strong>}</div>
 <p className="power">+{fmt(clickValue)} per click • {fmt(cps)}/sec • {g.purchased.length}/200 upgrades</p><div className="actions"><button onClick={()=>setBuyMode(buyMode==="max"?1:buyMode===3?"max":buyMode+1)}>BUY: {buyMode==="max"?"MAX":buyMode}×</button><button onClick={ascend}>ASCEND</button><button onClick={exportSave}>EXPORT</button><button onClick={importSave}>IMPORT</button><button onClick={reset}>RESET</button></div></div>
 <aside className="shop">{tab==="shop"&&<><h2>🏭 100 BUILDINGS</h2>{BUILDINGS.map(b=>{const n=g.buildings[b.id]||0,cost=Math.floor(b.base*Math.pow(1.15,n));return <button className={"building "+(g.cookies>=cost?"ok":"")} key={b.id} onClick={()=>buyBuilding(b)}><span>{b.icon}</span><div><b>{b.name}</b><small>{fmt(b.cps)} / sec each</small></div><div className="right"><b>{n}</b><small>🍪 {fmt(cost)}</small></div></button>})}</>}
 {tab==="upgrades"&&<><h2>🧪 200 UPGRADES</h2>{UPGRADES.map(u=>{const done=g.purchased.includes(u.id);return <button className={"building "+(done?"done":g.cookies>=u.cost?"ok":"")} disabled={done} key={u.id} onClick={()=>buyUpgrade(u)}><span>{done?"✅":"⬆️"}</span><div><b>{u.name}</b><small>{done?"Purchased":u.desc}</small></div><div className="right"><small>{done?"DONE":"🍪 "+fmt(u.cost)}</small></div></button>})}</>}
 {tab==="achievements"&&<><h2>🏆 MILESTONES</h2>{ACHIEVEMENTS.map(a=><div className={"achievement "+(unlock(a)?"unlocked":"")} key={a[0]}><span>{unlock(a)?"🏆":"🔒"}</span><div><b>{a[1]}</b><small>Target: {fmt(a[2])}</small></div></div>)}</>}
 {tab==="research"&&<Research g={g} setG={setG}/>}
 {tab==="garden"&&<div className="research"><h2>🌱 REALITY GARDEN</h2><p>Sugar lumps: <b>{g.sugar}</b> • Plants: <b>{g.plants.length}</b></p><button className="bigBtn" onClick={plant}>PLANT 1 SUGAR LUMP</button><p>Each planted specimen grants +8% production. Sugar slowly grows while you play.</p></div>}
 {tab==="spells"&&<div className="research"><h2>🔮 SPELLBOOK</h2><p>Mana: <b>{g.mana.toFixed(0)}/{g.maxMana}</b> • Spells cast: <b>{g.spells}</b></p><button className="researchNode" onClick={()=>castSpell("luck")}><b>✨ Fortune</b><small>Summon a golden cookie • 20 mana</small></button><button className="researchNode" onClick={()=>castSpell("storm")}><b>⚡ Cookie Storm</b><small>20 seconds of 7× production • 60 mana</small></button><button className="researchNode" onClick={()=>castSpell("alchemy")}><b>⚗️ Alchemy</b><small>Create 30 seconds of production • 100 mana</small></button></div>}
 {tab==="market"&&<div className="research"><h2>📈 BAKERY MARKET</h2><p>Trade cookies for rare relics. Prices fluctuate in future updates.</p><button className="bigBtn" onClick={tradeStock}>TRADE 1,000 COOKIES</button><p>Completed trades: <b>{g.trades}</b> • Relics: <b>{g.relics}</b></p></div>}
 {tab==="seasons"&&<div className="research"><h2>🌎 SEASONS</h2><p>Current season: <b>{season}</b></p>{["Harvest","Frost","Arcane","Cosmic","Festival"].map((x,i)=><button className={"researchNode "+(season===x?"ok":"")} key={x} onClick={()=>setG(v=>({...v,season:i}))}><b>{x}</b><small>{i===0?"+15% production":i===1?"+20% offline efficiency":i===2?"Mana regenerates faster":i===3?"+50% golden rewards":"Clicks can trigger mini-frenzy"}</small></button>)}</div>}
 
 {tab==="ascension"&&<div className="research"><h2>🌌 ASCENSION</h2><p>Turn lifetime bakery power into permanent cosmic progression.</p><h3>{fmt(Math.floor(Math.cbrt(g.total/1e6)))} heavenly levels</h3><p>Each level grants +5% production after the reset.</p><button className="bigBtn" onClick={ascend}>ASCEND NOW</button></div>}
 {tab==="stats"&&<div className="research"><h2>📊 BAKERY DATA</h2><p>Total baked: <b>{fmt(g.total)}</b></p><p>Clicks: <b>{fmt(g.clicks)}</b></p><p>Golden cookies: <b>{fmt(g.goldenClicks)}</b></p><p>Best combo: <b>{fmt(g.bestCombo)}</b></p><p>Buildings: <b>{fmt(owned)}</b></p><p>Upgrades: <b>{g.purchased.length}/200</b></p><p>Heavenly levels: <b>{fmt(g.heaven)}</b></p><p>Production multiplier: <b>×{(g.multiplier*upgradeMult*(1+g.heaven*.05)).toFixed(2)}</b></p></div>}</aside></section>
 <section className="megaPanel"><h2>🧨 MEGA CONTENT VAULT</h2><div className="megaGrid"><div><b>{ACHIEVEMENT_PACK.length}</b><small>dynamic achievements</small></div><div><b>{EVENT_PACK.length}</b><small>random events</small></div><div><b>{RELIC_PACK.length}</b><small>relics</small></div><div><b>{SPELL_PACK.length}</b><small>spells</small></div><div><b>{QUEST_PACK.length}</b><small>quests</small></div></div><p>These systems are data-driven so the universe can scale without manually duplicating UI code.</p></section><footer>COOKIE REALMS • 100 buildings • 200 upgrades • prestige • research • golden events • offline progress • local saves</footer></main>;
}

function Research({g,setG}){const nodes=[["r1","Efficient Ovens","+10% production",100],["r2","Golden Radar","+10% golden rewards",500],["r3","Quantum Hands","+25% click power",2000],["r4","Time Compression","+50% offline efficiency",10000],["r5","Reality Baking","+100% production",50000],["r6","Infinite Research","+250% production",500000]];return <div className="research"><h2>🔬 RESEARCH LAB</h2><p>Research points: <b>{fmt(g.research)}</b></p>{nodes.map(n=><button className="researchNode" key={n[0]} onClick={()=>{if(g.research<n[3])return;setG(x=>({...x,research:x.research-n[3],multiplier:x.multiplier*1.1}))}}><b>{n[1]}</b><small>{n[2]} • {fmt(n[3])} RP</small></button>)}<button className="bigBtn" onClick={()=>setG(x=>({...x,research:x.research+Math.max(1,Math.floor(x.total/1e6))}))}>CONVERT POWER → RESEARCH</button></div>}
